# -----------------------------------------------------------------------
#  environment.yml
#  Reproducible Conda environment for EFANet
#  Target: CUDA 11.8  |  Python 3.10  |  PyTorch 2.2
#  Covers: training, evaluation (LPIPS/PIQ), statistical analysis,
#          ONNX / TensorRT export, Jupyter notebooks.
# -----------------------------------------------------------------------
name: efanet
channels:
  - pytorch # official PyTorch channel (CUDA-enabled builds)
  - nvidia # TensorRT, cuDNN
  - conda-forge # scientific stack & misc.
dependencies:
  # --- core language & toolchain ---------------------------------------
  - python=3.10
  - pip>=23.3
  - cudatoolkit=11.8 # pinned to match official torch wheels
  - cudnn # pulls the CUDA 11.8–compatible build
  # --- deep-learning stack --------------------------------------------
  - pytorch=2.2.*=cuda118* # ensure CUDA 11.8 build
  - torchvision=0.17.*=cuda118*
  - torchaudio=2.2.*=cuda118*
  - tensorboard>=2.15 # training curves
  # --- computer-vision / data -----------------------------------------
  - opencv>=4.9
  - scikit-image>=0.22
  - pillow>=10.3
  - albumentations>=1.3 # data augmentation (conda-forge build)
  # --- scientific & metrics -------------------------------------------
  - numpy>=1.24
  - scipy>=1.11
  - pandas>=2.2
  - tqdm>=4.66
  - statsmodels>=0.14 # ANOVA & Tukey HSD
  - scikit-learn>=1.4
  - matplotlib>=3.8
  - seaborn>=0.13
  # --- deployment / export --------------------------------------------
  - onnx>=1.15
  - onnxruntime-gpu>=1.17
  - tensorrt # nvidia channel (matching CUDA 11.8)
  # --- development & notebooks ----------------------------------------
  - ipykernel
  - jupyterlab
  - black # code formatter
  - pytest # unit tests
  # --- pip-only packages ----------------------------------------------
  - pip:
      # model zoo / weight init
      - timm>=0.9.12
      # perceptual & image-quality metrics
      - lpips==0.1.4
      - piq>=0.8.1
      # downstream face-recognition evaluation
      - deepface>=0.0.79
      # configuration helpers
      - hydra-core>=1.3
      - yacs>=0.1.8
      # utilities
      - tabulate>=0.9
